### ISSUE TITLE
Add .lando.yml to support local Lando environment

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/iiedorg#108]
Hi @cbrody 

I've finally got my Drupal 7 iied.org local working with Lando. 

To share this between us, it would be good to commit the .lando.yml file to the repo.

I'll create a branch and a merge request for your review so we can hopefully all benefit from a consistent environment if needed. 

Open to other suggestions, naturally. 

Many thanks,

Finn

**Comment by cbrody** [comment]
Hi Finn,

That makes sense, please go ahead and create a pull request.

best,
Chris

**Comment by cbrody** [comment]
Looks good to go, merging.
